### PR TITLE
Add Open Run JavaScript window shortcut

### LINKED ISSUE #189: Shortcut for "Run JavaScript" window
I think it would be nice to have a shortcut for opening Zotero's "Run JavaScript" window.

I'll create a PR for this.

### PR DESCRIPTION
**Pull request by qqobb**
Closes #189.

### CODE REVIEW

**Comment by wshanks** [comment]
Thanks for propagating to all the locale files!

**Comment by wshanks** [comment]
@qqobb thanks for you contributions -- would you like to be added as a collaborator for the repo?

**Comment by wshanks** [comment]
Sorry for the delay in getting back to this. In practice, for now, I think the main implication is just that it will look a little more official if you comment on an issue or pull request.

A collaborator has the ability to merge pull requests but since it is just the two of us you can just approve a PR and leave the merging / releasing to me for now. If we get more collaborators, maybe it would make sense to spread out the merging responsibilities.

I make the releases with https://github.com/wshanks/release.py (just a script I wrote) using the `deploy/config.yaml` configuration file in the repo. As with most things around Zutilo, there is a tension between improving the release and leaving it alone because it works well enough. If I had unlimited free time, I would set up a GitHub Action to do the release.

**Comment by qqobb** [comment]
No problem, thanks for the invitation! So, for now, I will mostly try to help with managing some of the issues and pull requests. Without prior discussion I won't merge PRs, but I might close issues if that seems appropriate.

I also thought using GitHub Actions for test builds and releases could be nice. But before looking into that, we could consider simplifying the Makefile. I never found the integrated README document very useful. Navigating and reading the long document in a small window isn't convenient, so linking to the online docs instead might be more helpful. One could then have links such as [Command Reference](https://github.com/wshanks/Zutilo/blob/master/docs/COMMANDS.md#readme) in About Zutilo and remove the Pandoc command from the Makefile. If the GitHub directories are also organized in the same way as in the XPI file, one could download the [zipball](https://github.com/wshanks/zutilo/zipball/master/) of the Zutilo master, re-zip, and install. This works for ZotFile. Writing GitHub Actions might also be easier with such changes. I could try to help with that, but probably not in the near future.

**Comment by wshanks** [comment]
Yes, I agree that the integrated README is not that useful. I think zipping the addon/ directory now might work (you will get an error if you try to open the integrated README) but I haven't tested it recently. For the readme, we could use GitHub pages with a static site generator that turns markdown into html like MkDocs or Sphinx.

**Pull request merged**
