### PR TITLE
Add batch editing of item types

### LINKED ISSUE #162: Batch edit 'item type' ?
Hello, I hope I didn't look over it, but after a scan of the documentation and context menu items, I don't seem to find a way to batch edit/change item types (book, article, document, etc..) of zotero items. Does this feature exist or is there a way to accomplish this using Zutilo? From my understanding of the book <-> book section feature Zutilo should be able to accomplish this.. ?

Regardless of the above, thanks a lot for having made batch edit of item fields possible. I stumbled upon this future recently and I love it!

### PR DESCRIPTION
**Pull request by qqobb**
Closes #162

### CODE REVIEW

**Comment by wshanks** [comment]
It is nice how small of a code change this is, but I think it might hide the feature too much. What about making a new "Paste item type" function that just pastes the item type? I think this would not require much more code.

**Comment by qqobb** [comment]
Ok, I agree that a separate "Paste item type" function might be clearer. One advantage would be that one doesn't have to edit the JSON for changing item types.

I added a commit for the new function. This is not tested. Let me know if you want me to merge the commits. (I would need to check how to do this.)

**Comment by qqobb** [comment]
There was an issue with the original version of the "Paste item type" function. I added a fix and it's working now. Sorry about that.

**Comment by wshanks** [comment]
No problem -- I actually was looking at the old version right when you pushed and saw the refresh button appear on the page. This version looks good to me.

I can take care of cleaning up the commits. The way I usually do it is `git rebase -i master` with the branch checked out and then change `pick` to `squash` for every commit after the first one. GitHub also has an option to do this automatically but I haven't tried it.

**Comment by qqobb** [comment]
It would be nice if you could take care of cleaning up the commits. (Are you doing `git push origin +master` after squashing?)

I guess you might want to include these changes:
- Add changes of COMMANDS to the other locales.
- Edit the CHANGELOG. (I wasn't sure about the version number.)

You could also consider changing the name of the "Copy item fields" function. Maybe "Copy item type and fields" is more fitting now.

**Comment by wshanks** [comment]
I cleaned up the commits and took care of the locales.

**Comment by qqobb** [comment]
Thanks! Updating to version 3.6.0 went well.

**Comment by floriandierickx** [comment]
Wonderful, thanks a lot for this feature @qqobb and @wshanks ! I just tried it out and it works like a charm, you just made me gain hours and hours of batch editing time :))))

**Pull request merged**
