### PR TITLE
fixed 2 typos

### PR DESCRIPTION
**Pull request by fflamerie**
Translating this file into French, I have identified what seems to me to be 2 typing errors

### CODE REVIEW

**Comment by wshanks** [comment]
Thanks for all the updates!

**Comment by fflamerie** [comment]
Thanks for your feedback! Did you get my email regarding the translations into French of USAGE. md and COMMANDS.md files?

**Comment by wshanks** [comment]
Oh, I did but I read it too quickly and thought you were asking about the PR's that you did open. It would be fine to submit a PR with translations of the md files. I have tried to format the markdown as one line per sentence to ease with translation, so please try to keep that formatting. So far those files haven't been translated, so let me know if you have suggestions for making it easier to translate them.

**Comment by fflamerie** [comment]
Thanks, I have submitted the 2 files, line numbering is kept identical. I have translated but not fully understood the following section : https://github.com/wshanks/Zutilo/blob/master/docs/USAGE.md#attaching-browser-content-to-item :
* I could not find how to attach a web link or the current web page to the currently selected item,
* I do not understand why ZotFile is mentioned when it is the subject of the previous paragraph.

**Pull request merged**
